#!/bin/bash
cd /home/arsene/pd-externals/Fraise/testarray/exampleFruit
PATH=$PATH:/home/arsene/pd-externals/Fraise/bin/utils
PATH=$PATH:/home/arsene/pd-externals/Fraise/bin/linux64
rm -f /home/arsene/pd-externals/Fraise/testarray/exampleFruit/exampleFruit.map
rm -f /home/arsene/pd-externals/Fraise/testarray/exampleFruit/make.err
mkdir -p "exampleFruit-objs/fruit"
/home/arsene/pd-externals/Fraise/bin/linux64/sdcc --use-stdout -I"/home/arsene/pd-externals/Fraise/fruit" -I"/home/arsene/pd-externals/Fraise/eeparams" -I"/home/arsene/pd-externals/Fraise/core" -I"/home/arsene/pd-externals/Fraise/fraisedevice" -DUD_SETUP -DUD_LOOP -DUD_RCVC -DUD_RCV -DUD_HIGH -I. -mpic16 --vc --denable-peeps --optimize-cmp --optimize-df --obanksel=2 --opt-code-speed --fomit-frame-pointer --use-non-free --std-sdcc99 -p18f26k22 -I"/home/arsene/pd-externals/Fraise/boards/Versa2" -I"/home/arsene/pd-externals/Fraise/bin/share/non-free/include/pic16" -I"/home/arsene/pd-externals/Fraise/bin/share/include/pic16" -c "/home/arsene/pd-externals/Fraise/fruit/fruit.c" -o "exampleFruit-objs/fruit/fruit.o" >> make.err
mkdir -p "exampleFruit-objs/eeparams"
/home/arsene/pd-externals/Fraise/bin/linux64/sdcc --use-stdout -I"/home/arsene/pd-externals/Fraise/fruit" -I"/home/arsene/pd-externals/Fraise/eeparams" -I"/home/arsene/pd-externals/Fraise/core" -I"/home/arsene/pd-externals/Fraise/fraisedevice" -DUD_SETUP -DUD_LOOP -DUD_RCVC -DUD_RCV -DUD_HIGH -I. -mpic16 --vc --denable-peeps --optimize-cmp --optimize-df --obanksel=2 --opt-code-speed --fomit-frame-pointer --use-non-free --std-sdcc99 -p18f26k22 -I"/home/arsene/pd-externals/Fraise/boards/Versa2" -I"/home/arsene/pd-externals/Fraise/bin/share/non-free/include/pic16" -I"/home/arsene/pd-externals/Fraise/bin/share/include/pic16" -c "/home/arsene/pd-externals/Fraise/eeparams/eeparams.c" -o "exampleFruit-objs/eeparams/eeparams.o" >> make.err
mkdir -p "exampleFruit-objs/core"
/home/arsene/pd-externals/Fraise/bin/linux64/sdcc --use-stdout -I"/home/arsene/pd-externals/Fraise/fruit" -I"/home/arsene/pd-externals/Fraise/eeparams" -I"/home/arsene/pd-externals/Fraise/core" -I"/home/arsene/pd-externals/Fraise/fraisedevice" -DUD_SETUP -DUD_LOOP -DUD_RCVC -DUD_RCV -DUD_HIGH -I. -mpic16 --vc --denable-peeps --optimize-cmp --optimize-df --obanksel=2 --opt-code-speed --fomit-frame-pointer --use-non-free --std-sdcc99 -p18f26k22 -I"/home/arsene/pd-externals/Fraise/boards/Versa2" -I"/home/arsene/pd-externals/Fraise/bin/share/non-free/include/pic16" -I"/home/arsene/pd-externals/Fraise/bin/share/include/pic16" -c "/home/arsene/pd-externals/Fraise/core/core.c" -o "exampleFruit-objs/core/core.o" >> make.err
mkdir -p "exampleFruit-objs/fraisedevice"
/home/arsene/pd-externals/Fraise/bin/linux64/sdcc --use-stdout -I"/home/arsene/pd-externals/Fraise/fruit" -I"/home/arsene/pd-externals/Fraise/eeparams" -I"/home/arsene/pd-externals/Fraise/core" -I"/home/arsene/pd-externals/Fraise/fraisedevice" -DUD_SETUP -DUD_LOOP -DUD_RCVC -DUD_RCV -DUD_HIGH -I. -mpic16 --vc --denable-peeps --optimize-cmp --optimize-df --obanksel=2 --opt-code-speed --fomit-frame-pointer --use-non-free --std-sdcc99 -p18f26k22 -I"/home/arsene/pd-externals/Fraise/boards/Versa2" -I"/home/arsene/pd-externals/Fraise/bin/share/non-free/include/pic16" -I"/home/arsene/pd-externals/Fraise/bin/share/include/pic16" -c "/home/arsene/pd-externals/Fraise/fraisedevice/fraisedevice.c" -o "exampleFruit-objs/fraisedevice/fraisedevice.o" >> make.err
/home/arsene/pd-externals/Fraise/bin/linux64/sdcc --use-stdout -DUD_SETUP -DUD_LOOP -DUD_RCVC -DUD_RCV -DUD_HIGH -I. -mpic16 --vc --denable-peeps --optimize-cmp --optimize-df --obanksel=2 --opt-code-speed --fomit-frame-pointer --use-non-free --std-sdcc99 -p18f26k22 -I"/home/arsene/pd-externals/Fraise/boards/Versa2" -I"/home/arsene/pd-externals/Fraise/bin/share/non-free/include/pic16" -I"/home/arsene/pd-externals/Fraise/bin/share/include/pic16" -c "/home/arsene/pd-externals/Fraise/core/crt0iz-rloc.c" -o "exampleFruit-objs/crt.o" >> make.err
/home/arsene/pd-externals/Fraise/bin/linux64/sdcc --use-stdout -DUD_SETUP -DUD_LOOP -DUD_RCVC -DUD_RCV -DUD_HIGH -I. -mpic16 --vc --denable-peeps --optimize-cmp --optimize-df --obanksel=2 --opt-code-speed --fomit-frame-pointer --use-non-free --std-sdcc99 -p18f26k22 -I"/home/arsene/pd-externals/Fraise/boards/Versa2" -I"/home/arsene/pd-externals/Fraise/bin/share/non-free/include/pic16" -I"/home/arsene/pd-externals/Fraise/bin/share/include/pic16" -c "/home/arsene/pd-externals/Fraise/boards/Versa2/boardconfig.c" -o "exampleFruit-objs/boardconfig.o" >> make.err
/home/arsene/pd-externals/Fraise/bin/linux64/sdcc --use-stdout -DUD_SETUP -DUD_LOOP -DUD_RCVC -DUD_RCV -DUD_HIGH -I. -mpic16 --vc --denable-peeps --optimize-cmp --optimize-df --obanksel=2 --opt-code-speed --fomit-frame-pointer --use-non-free --std-sdcc99 -p18f26k22 -I"/home/arsene/pd-externals/Fraise/boards/Versa2" -I"/home/arsene/pd-externals/Fraise/bin/share/non-free/include/pic16" -I"/home/arsene/pd-externals/Fraise/bin/share/include/pic16" --use-crt="exampleFruit-objs/crt.o" -L"/home/arsene/pd-externals/Fraise/bin/share/lib/pic16" -L"/home/arsene/pd-externals/Fraise/bin/share/non-free/lib/pic16" -Wl"-O 1 -m -w -s /home/arsene/pd-externals/Fraise/boards/Versa2/board.lkr" -o "exampleFruit.hex" libsdcc.lib libc18f.lib libdev18f26k22.lib libm18f.lib "exampleFruit-objs/boardconfig.o" "exampleFruit-objs/exampleFruit.o" "exampleFruit-objs/fruit/fruit.o" "exampleFruit-objs/eeparams/eeparams.o" "exampleFruit-objs/core/core.o" "exampleFruit-objs/fraisedevice/fraisedevice.o" >> make.err
echo make_done | to_pd 41424
